=== Evoke-Platform/evoke-sdk/widgetschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "WidgetProperties",
    "type": "object",
    "required": ["id", "name", "properties"],
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string",
            "description": "Unique identifier for the widget"
        },
        "name": {
            "type": "string",
            "description": "Name of the widget"
        },
        "description": {
            "type": "string",
            "description": "Description of the widget"
        },
        "version": {
            "type": "string",
            "description": "Version of the widget"
        },
        "src": {
            "type": "string",
            "description": "URL of the widget source code"
        },
        "needsDataSource": {
            "type": "boolean",
            "description": "Indicates if the widget needs a data source"
        },
        "needsInstance": {
            "oneOf": [{ "type": "boolean" }, { "$ref": "#/definitions/dataType" }]
        },
        "typesSupported": {
            "type": "array",
            "items": { "$ref": "#/definitions/dataType" }
        },
        "needsDocument": {
            "oneOf": [{ "type": "boolean" }, { "$ref": "#/definitions/dataType" }]
        },
        "icon": {
            "type": "object",
            "required": ["src"],
            "additionalProperties": false,
            "properties": {
                "src": {
                    "type": "string"
                }
            }
        },
        "allowSticky": {
            "type": "boolean"
        },
        "allowChildren": {
            "type": "boolean",
            "description": "Indicates that the widget is a container; the contained page items are passed to the component as children"
        },
        "deprecated": {
            "type": "boolean"
        },
        "betaRelease": {
            "type": "boolean"
        },
        "properties": {
            "type": "array",
            "uniqueItems": true,
            "description": "Array of properties that the widget supports",
            "items": { "$ref": "#/definitions/widgetProperty" }
        },
        "$schema": { "type": "string" }
    },

    "definitions": {
        "dataType": {
            "enum": [
                "documents",
                "objectInstances",
                "documentVersions",
                "relatedObjectInstances",
                "relatedPeerObjectInstances"
            ]
        },
        "choices": {
            "type": "array",
            "uniqueItems": true,
            "description": "Array of choices for the property",
            "items": {
                "$ref": "#/definitions/choice"
            }
        },
        "presetValues": {
            "type": "array",
            "uniqueItems": true,
            "description": "Array of preset values available for selection within the filter properties",
            "items": {
                "$ref": "#/definitions/choice"
            }
        },
        "choice": {
            "type": "object",
            "required": ["label", "value"],
            "additionalProperties": false,
            "properties": {
                "value": {
                    "type": "string",
                    "description": "Value of the choice"
                },
                "label": {
                    "type": "string",
                    "description": "Label of the choice"
                }
            }
        },
        "api": {
            "type": "object",
            "required": ["url", "resultMapping"],
            "additionalProperties": false,
            "properties": {
                "url": {
                    "type": "string",
                    "description": "URL of the API"
                },
                "resultMapping": {
                    "type": "object",
                    "required": ["value", "label"],
                    "additionalProperties": false,
                    "properties": {
                        "value": {
                            "type": "string",
                            "description": "Value of the API result"
                        },
                        "label": {
                            "type": "string",
                            "description": "Label of the API result"
                        }
                    },
                    "description": "Mapping of the API result to the choices"
                },
                "mappedValues": {
                    "type": "object",
                    "description": "Values from other widget properties used to replace parts of the url. The key specifies the url segment to replace, and the value indicates the property name."
                }
            }
        },
        "inputGroup": {
            "type": "array",
            "uniqueItems": true,
            "items": { "$ref": "#/definitions/widgetProperty" }
        },
        "widgetProperty": {
            "type": "object",
            "required": ["name", "type"],
            "additionalProperties": false,
            "oneOf": [
                {
                    "properties": { "type": { "const": "inputGroup" } },
                    "required": ["inputGroup"]
                },
                {
                    "properties": { "type": { "const": "system" } }
                },
                {
                    "properties": { "type": { "const": "text" } }
                },
                {
                    "properties": { "type": { "const": "number" } }
                },
                {
                    "properties": { "type": { "const": "date" } }
                },
                {
                    "properties": { "type": { "const": "boolean" } }
                },
                {
                    "properties": { "type": { "const": "choices" } },
                    "oneOf": [{ "required": ["choices"] }, { "required": ["api"] }]
                },
                {
                    "properties": { "type": { "const": "actionButtons" } }
                },
                {
                    "properties": { "type": { "const": "documentUpload" } }
                },
                {
                    "properties": {
                        "type": { "const": "columnSelector" },
                        "tooltip": false
                    }
                },
                {
                    "properties": { "type": { "const": "filter" } }
                }
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "description": "This is the name of the input field, and also the property name passed to the widget react component"
                },
                "type": {
                    "type": "string",
                    "description": "This is the “type” of the input and will determine which input field(s) are presented to the builder user, and the format of the values passed to the widget.",
                    "enum": [
                        "text",
                        "number",
                        "boolean",
                        "choices",
                        "inputGroup",
                        "date",
                        "actionButtons",
                        "documentUpload",
                        "columnSelector",
                        "filter"
                    ]
                },
                "displayName": {
                    "type": "string",
                    "description": "The text that shows up in the list of widget-settings while editing a widget. If “displayName” is not specified, the value specified for “name” is displayed in start-case."
                },
                "instructionText": {
                    "type": "string",
                    "description": "This value shows up as a prompt at the top of all the input field(s) for that setting."
                },
                "isOptional": {
                    "type": "boolean",
                    "description": "Indicates if the property is optional"
                },
                "isWidgetTitle": {
                    "type": "boolean"
                },
                "isMultiple": {
                    "type": "boolean",
                    "description": "Indicates if a property can have multiple values. Currently only supported for choices and inputGroup properties"
                },
                "initialValue": {
                    "oneOf": [{ "type": "string" }, { "type": "number" }, { "type": "boolean" }, { "type": "object" }],
                    "description": "Initial value of the property"
                },
                "tooltip": {
                    "type": "string",
                    "description": "This value shows up as a tooltip when the user hovers over the input field."
                },
                "informationModal": {
                    "type": "object",
                    "properties": {
                        "linkText": { "type": "string" },
                        "title": { "type": "string" },
                        "content": { "type": "string" },
                        "isJson": { "type": "boolean" }
                    }
                },
                "hidden": {
                    "type": "object",
                    "properties": {
                        "dataType": {
                            "type": "array",
                            "items": { "$ref": "#/definitions/dataType" }
                        }
                    }
                },
                "isSortable": {
                    "type": "boolean"
                },
                "choices": { "$ref": "#/definitions/choices" },
                "api": {
                    "$ref": "#/definitions/api"
                },
                "inputGroup": { "$ref": "#/definitions/inputGroup" },
                "presetValues": {
                    "$ref": "#/definitions/presetValues"
                },
                "disabled": {
                    "type": "object",
                    "properties": {
                        "dataType": {
                            "type": "array",
                            "items": { "$ref": "#/definitions/dataType" }
                        }
                    }
                },
                "visibility": { "$ref": "#/definitions/widgetVisibilityGroup" },
                "itemDisplayName": {
                    "type": "string",
                    "description": "Specifies the label for the singular repeated item within a multiple inputGroup property"
                }
            }
        },
        "widgetVisibilityGroup": {
            "type": "object",
            "description": "Group of conditions for the visibility of a widget property",
            "properties": {
                "operator": {
                    "type": "string",
                    "enum": ["and", "or"]
                },
                "conditions": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/widgetVisibilityCondition" }
                }
            },
            "required": ["operator", "conditions"]
        },
        "widgetVisibilityCondition": {
            "type": "object",
            "description": "Condition for the visibility of a widget property",
            "properties": {
                "field": { "type": "string", "description": "Name of the widget property to be compared" },
                "operator": {
                    "type": "string",
                    "enum": ["equals", "notEquals"]
                },
                "value": {
                    "anyOf": [
                        { "type": "string" },
                        { "type": "number" },
                        { "type": "boolean" },
                        { "type": "object" },
                        { "type": "array" }
                    ]
                }
            },
            "required": ["field", "operator", "value"]
        }
    }
}

=== Evoke-Platform/evoke-sdk/packages/plugin/src/generators/app/templates/src/widgets/SampleWidget/WidgetProperties.json
{
    "id": "Widget",
    "name": "Sample widget",
    "description": "Description of the Sample Widget",
    "version": "1.0.0",
    "src": "src/widgets/SampleWidget",
    "properties": [
        {
            "name": "message",
            "type": "text",
            "isOptional": true,
            "displayName": "Message"
        }
    ]
}
